config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'index#input'
  get 'index/input'
  get 'index/output'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
# frozen_string_literal: true

class IndexController < ApplicationController
  def input; end

  def output
    @arr = []
    @array = []
    @array2 = []
    first = 1
    factorial = 1
    fac_num = 1
    count = 0
    while count < 4
      @arr.push('No')
      num = first * (first + 1) * (first + 2)
      if factorial < num
        factorial = (factorial * (fac_num + 1))
        fac_num += 1
      elsif factorial == num
        @array.push(fac_num)
        @array2.push(first)
        first += 1
        count += 1
        @arr.push('Yes')
      else
        first += 1
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/index_helper.rb
# frozen_string_literal: true

module IndexHelper
end

app/views/index/input.html.erb
<h1>Проверка гипотезы Симона</h1>
<p>Существует гипотеза Симона о факториале. Она гласит, что существует
  4 факториала, которые представимы в виде произведения трех последовательных
  чисел. Например: 4! =2.3.4. Написать программу, определяющую эту четверку,
  подсчитать действительное количество таких факториалов, если это возможно и
  тем самым доказать неправильность гипотезы. Вывести на печать результаты
  каждой итерации и финальных расчетов</p>
<form action="<%= index_output_url %>">
  <input type="submit" value="Решение">
</form>

app/views/index/output.html.erb
<h3>Все итерации</h3>
<p>Если написано yes, значит на этой итерации было найдено одно из чисел, подходящих под ответ</p>
<table border="1">
  <tr>
    <th>Iteration number</th>
    <th>Result</th>
  </tr>
  <% @arr.each_with_index do |y, i|%>
    <tr>
      <td><%= i + 1 %></td>
      <td><%= y %></td>
    </tr>
  <% end %>
</table>
<h3>Все факториалы, представимые в виде произведения трёх идущих подряд чисел</h3>
<table border = '1'>
  <tr>
    <th>Factorial</th>
    <th>First number</th>
    <th>Second number</th>
    <th>Third number</th>
  </tr>
  <% @array.each_with_index  do |x, i|%>
    <tr>
      <td>
        <%= x %>
      </td>
      <td>
        <%= @array2[i] %>
      </td>
      <td>
        <%= @array2[i] + 1 %>
      </td>
      <td>
        <%= @array2[i] + 2 %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>